name: 'Jest Coverage Comment Action'
description: 'Comments a PR with the coverage (jest)'
inputs:
  github-token:
    description: 'Github token'
    required: true
  jest-command:
    description: 'The jest command'
    required: false
    default: 'npx jest --coverage'
runs:
  using: 'node12'
  main: 'index.js'
